import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_GB': {
          'Choose Section:': 'Choose Section:',
          "Information Technology": "Information Technology",
          "Information Technology - not available": "Information Technology - not available",
          "Information Technology - old": "Information Technology - old",
          "Technology": "Technology",
          "Economy & Management": "Economy & Management",
          "Science": "Science",
          "Math": "Math",
          "Literature": "Literature",
          "Sport": "Sport",
          "Home": "Home",
          "Made by Louay Ghanney": "Made by Louay Ghanney",
          "Copied to clipboard": "Copied to clipboard",
          "Average": "Average",
          "Algorithms": "Algorithms",
          "Physics": "Physics",
          "TIC": "TIC",
          "DataBases": "DataBases",
          "STI": "STI",
          "French": "French",
          "English": "English",
          "Experemental Science": "Experemental Science",
          "Arabic": "Arabic",
          "Philosophy": "Philosophy",
          "His/Geo": "His/Geo",
          "Economy": "Economy",
          "Management": "Management",
          "Sport-SP": "Sport-SP",
          "Physical Edu": "Physical Edu",
          "Calculate": "Calculate",
          "FG:": "GF:",
          "Section: ": "Section: ",
        },
        'fr_FR': {
          'Choose Section:': 'Choisissez votre Section:',
          "Information Technology": "Informatique",
          "Information Technology - not available": "Informatique - non disponible",
          "Information Technology - old": "Informatique Ancien Regime",
          "Technology": "Techniques",
          "Economy & Management": "Economie et Gestion",
          "Science": "Science",
          "Math": "Mathematiques",
          "Literature": "Lettres",
          "Sport": "Sport",
          "Home": "Acceuil",
          "Made by Louay Ghanney": "Crée par Louay Ghanney",
          "Copied to clipboard": "copié dans le presse-papier",
          "Average": "Moyen",
          "Algorithms": "Algorithmes",
          "Physics": "Physique",
          "TIC": "TIC",
          "DataBases": "Bases de données",
          "STI": "STI",
          "French": "Français",
          "English": "Anglais",
          "Experemental Science": "Sciences Expérimentales",
          "Arabic": "Arabe",
          "Philosophy": "Philosophie",
          "His/Geo": "His/Geo",
          "Economy": "Economie",
          "Management": "Gestion",
          "Sport-SP": "SP-Sport",
          "Physical Edu": "Édu Physique",
          "Calculate": "Calculer",
          "FG:": "FG:",
          "Section: ": "Section: ",
        },
        'ar_AR': {
          'Choose Section:': 'إختر شعبتك:',
          "Information Technology": "علوم الإعلامية",
          "Information Technology - not available": "علوم الإعلامية - غير متوفر",
          "Information Technology - old": "علوم الإعلامية - نضام قديم",
          "Technology": "علوم تقنية",
          "Economy & Management": "اقتصاد و تصرف",
          "Science": "علوم تجريبية",
          "Math": "رياضيات",
          "Literature": "اداب",
          "Sport": "رياضة",
          "Home": "الصفحة الرئيسية",
          "Made by Louay Ghanney": "من صنع لؤي غنّاي",
          "Copied to clipboard": "نسخ الى الحافضة",
          "Average": "المعدل",
          "Algorithms": "الخوارزميات",
          "Physics": "الفيزياء",
          "TIC": "تكنولوجيا المعلومات و الإتصالات",
          "DataBases": "قواعد البيانات",
          "STI": "أنضمة و تكنولوجيا المعلومات",
          "French": "فرنسية",
          "English": "إنجليزية",
          "Experemental Science": "علوم الحياة و الأرض",
          "Arabic": "العربية",
          "Philosophy": "الفلسفة",
          "His/Geo": "تاريخ و جغرافيا",
          "Economy": "إقتصاد",
          "Management": "تصرف",
          "Sport-SP": "إختصاص رياضي",
          "Physical Edu": "تربية بدنية",
          "Calculate": "احسب",
          "FG:": ":الصيغة الإجمالية",
          "Section: ": "الشعبة: ",
        },
      };
}
